home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre/', views.about, name='about'),
    path('contato/', views.contact, name='contact'),
]

plataform/urls.py
from django.urls import path, include
from . import views

app_name = 'plataform'


partners_patterns = [
    path('', views.partners, name='partners'),
    path('novo_parceiro/', views.partner_create, name='partner_create'),
    path('visualizar_parceiro/<int:id>', views.partner_view, name="partner_view"),
    path('alterar_parceiro/<int:id>', views.partner_update, name="partner_update"),
    path('excluir_parceiro/<int:id>', views.partner_delete, name="partner_delete"),
]

items_patterns = [
    path('', views.items, name='items'),
    path('novo_item/', views.item_create, name='item_create'),
    path('visualizar_item/<int:id>', views.item_view, name="item_view"),
    path('alterar_item/<int:id>', views.item_update, name="item_update"),
    path('excluir_item/<int:id>', views.item_delete, name="item_delete"),
    
    # Ajax para Saldo
    path('<int:pk>/json/', views.produto_json, name='produto_json'),

    path('nova_un_med/', views.un_med_create, name='un_med_create'),
    path('nova_categoria/', views.category_create, name='category_create'),
]

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('parceiros/', include(partners_patterns)),
    path('itens/', include(items_patterns)),
]

sig_sanlis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('activation.urls')),
    path('', include('home.urls')),
    path('painel/', include('plataform.urls')),
    path('painel/estoque/', include('stock.urls')),
]

home/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

home/views.py
from django.shortcuts import render
from django.http import HttpResponse


sig = 'SIG SANLIS | '

def home(request):
    title = sig + 'Home'
    return render(request, 'index.html', {'title': title})


def about(request):
    title = sig + 'Sobre'
    return render(request, 'about.html', {'title': title})


def contact(request):
    title = sig + 'Contato'
    return render(request, 'contact.html', {'title': title})

home/templates/about.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block container %}

<header class="header-wrapper">

    {% include 'header.html' %}

    <section id="header-about">
        <h2 id="titleAbout">SANLIS GESTÃO</h2>
        <br>
        <h1 id="subtitleAbout">Melhorar a eficiência dos processos através do treinamento e da gestão de arquivos.</h1>
    </section>

</header>

<main class="container">

    {% include 'about_container.html' %}

</main>

<footer class="backTop">
    <a href="{% url 'home:about' %}">
        <button><span><i class="fa fa-arrow-up"></i> Topo</span></button>
    </a>
</footer>

{% endblock %}

home/templates/about_container.html
<section class="card-container">

    <article class="card-text">
        <h2>Quem Somos</h2>
        <p id="aboutText1">
            Os serviços da SanLis são elaborados de acordo com a realidade de cada negócio 
            identificando e propondo soluções adequadas ao perfil de cada cliente.
        </p>
        <a href="{% url 'home:about' %}"><button class="btn"><span>Mais Informações</span></button></a>
    </article>

    <figure class="card">
        <div class="card-wrapper" id="image1">
            <h2>SOBRE</h2>
            <p>Quem Somos</p>
        </div>
    </figure>

</section>

<section class="card-container">

    <figure class="card">
        <div class="card-wrapper" id="image2">
            <h2>SOBRE</h2>
            <p>Nossa Equipe</p>
        </div>
    </figure>

    <article class="card-text">
        <h2>Nossa Equipe</h2>
        <p id="aboutText2">
            Nossa equipe atua a fim de identificar os 6 pilares ligados a melhoria 
            dos resultados. Esses pilares são: pessoas, métodos, processos, planejamento, 
            indicadores e tecnologia.
        </p>
        <a href="{% url 'home:about' %}"><button class="btn"><span>Mais Informações</span></button></a>
    </article>

</section>

<section class="card-container">

    <article class="card-text">
        <h2>Nossos Serviços</h2>
        <p id="aboutText3">
            <ul>
                <li>Reduzir despesas e eliminar desperdícios.</li>
                <li>Melhor a lucratividade e a longevidade dos resultados</li>
                <li>Analisar as interrupções nos processos em busca de um maior ganho de produtividade.</li>
            </ul>
        </p>
        <a href="{% url 'home:about' %}"><button class="btn"><span>Mais Informações</span></button></a>
    </article>

    <figure class="card">
        <div class="card-wrapper" id="image3">
            <h2>SOBRE</h2>
            <p>Nossos Serviços</p>
        </div>
    </figure>
    
</section>

home/templates/contact.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block container %}

<header class="header-wrapper">

    {% include 'header.html' %}

    <section id="header-contact">

        <h1 id="titleContact">Rota</h1>
        <h2 id="subtitleContact">Veja como chegar</h2>
        <section>
            <iframe id="rota" 
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d245795.56223344515!2d-48.07744593965978!3d-15.721717481080342!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a3d18df9ae275%3A0x738470e469754a24!2zQnJhc8OtbGlhLCBERg!5e0!3m2!1spt-BR!2sbr!4v1667769848635!5m2!1spt-BR!2sbr" 
                width="" height="" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </section>

    </section>

</header>

<main>

    <section class="form-contact">
        
        <h1>Entre em Contato</h1>
        <span id="company-email">Email: sanlisgestao@hotmail.com</span>

        <form class="form" action="{% url 'home:contact' %}" method="get">
            <label class="label">
                Nome: <br>
                <input class="input" type="text" name="name" id="name">
            </label>

            <label class="label">
                E-mail: <br>
                <input class="input" type="email" name="email" id="email">
            </label>

            <label class="label">
                Assunto: <br>
                <select class="select" name="subject" id="subject">
                    <option value="1">Assunto 1</option>
                    <option value="2">Assunto 2</option>
                    <option value="3">Assunto 3</option>
                    <option value="4">Assunto 4</option>
                    <option value="5">Assunto 5</option>
                </select>
            </label>

            <label class="label">
                Descrição: <br>
                <textarea class="textarea" name="description" id="description"></textarea>
            </label>

            <button class="btn"><span>Enviar</span></button>
        </form>

    </section>
    
</main>

{% endblock %}

home/templates/header.html
<section class="checkbox-container">

    <div class="checkbox-wrapper">

        <input type="checkbox" id="toggle">
        <label class="checkbox" for="toggle">
            <div class="trace"></div>
            <div class="trace"></div>
            <div class="trace"></div>
        </label>

        <div class="menu"></div>
        <nav class="menu-items">
            <ul>
                <li><a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="{% url 'home:about' %}">Sobre</a></li>
                <li><a href="{% url 'home:contact' %}">Contato</a></li>
                <li><a href="{% url 'plataform:dashboard' %}">Painel</a></li>
            </ul>
        </nav>

    </div>

</section>

home/templates/index.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block container %}

<header class="header-wrapper">
        
    {% include 'header.html' %}

    <section class="company">

        <h1 id="company-name">SANLIS TREINAMENTO E GESTÃO DE ARQUIVOS</h1>
        <h3>Endereço</h3>
        <h3 id="company-street">Rua Nome da Rua, 123</h3>
        <h3 id="company-district">Bairro: Nome</h3>
        <h3 id="company-city">Belo Horizonte / MG</h3>
        <h3 id="company-zipcode">CEP: 30.000-000</h3>

    </section>

    <section class="contacts">

        <a id="company-phone" href="">
            <p><i class="fa fa-phone"></i> 
                <span title="Telefone" id="company-phone">31 9999-9999</span>
            </p>
        </a>
        <a id="whatsappLink" href="https://web.whatsapp.com/" target="_blank">
            <p><i class="fa fa-whatsapp"></i> 
                <span title="Whatsapp" id="company-whastapp">31 99999-9999</span>
            </p>
        </a>

    </section>

    <section class="social-media">

        <a id="company-site" title="Blog" href="https://www.google.com/" target="_blank">
            <i class="fa fa-globe"></i></a>
        <a id="company-instagram" title="Instagram" href="https://www.instagram.com/" target="_blank">
            <i class="fa fa-instagram"></i></a>
        <a id="company-linkedin" title="Linkedin" href="https://www.linkedin.com/" target="_blank">
            <i class="fa fa-linkedin"></i></a>
        <a id="company-facebook" title="Facebook" href="https://www.facebook.com/" target="_blank">
            <i class="fa fa-facebook"></i></a>

    </section>

</header>

{% endblock %}