activation/urls.py
from django.urls import path
from . import views


app_name = 'activation'

urlpatterns = [
    path('registrar/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('sair/', views.logout, name='logout'),
    path('ativar_conta/<str:token>/', views.active_account, name="active_account"),

    path('empresas/', views.companies, name='companies'),
    path('nova_empresa/', views.company_create, name='company_create'),
    path('visualizar_empresa/<int:id>', views.company_view, name="company_view"),
    path('alterar_empresa/<int:id>', views.company_update, name="company_update"),
    path('excluir_empresa/<int:id>', views.company_delete, name="company_delete"),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre/', views.about, name='about'),
    path('contato/', views.contact, name='contact'),
]

plataform/urls.py
from django.urls import path, include
from . import views

app_name = 'plataform'


partners_patterns = [
    path('', views.partners, name='partners'),
    path('novo_parceiro/', views.partner_create, name='partner_create'),
    path('visualizar_parceiro/<int:id>', views.partner_view, name="partner_view"),
    path('alterar_parceiro/<int:id>', views.partner_update, name="partner_update"),
    path('excluir_parceiro/<int:id>', views.partner_delete, name="partner_delete"),
]

items_patterns = [
    path('', views.items, name='items'),
    path('novo_item/', views.item_create, name='item_create'),
    path('visualizar_item/<int:id>', views.item_view, name="item_view"),
    path('alterar_item/<int:id>', views.item_update, name="item_update"),
    path('excluir_item/<int:id>', views.item_delete, name="item_delete"),
    
    # Ajax para Saldo
    path('<int:pk>/json/', views.produto_json, name='produto_json'),

    path('nova_un_med/', views.un_med_create, name='un_med_create'),
    path('nova_categoria/', views.category_create, name='category_create'),
]

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('parceiros/', include(partners_patterns)),
    path('itens/', include(items_patterns)),
]

sig_sanlis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('activation.urls')),
    path('', include('home.urls')),
    path('painel/', include('plataform.urls')),
    path('painel/estoque/', include('stock.urls')),
]

activation/models.py
from django.db import models
from django.contrib.auth.models import User


class Company(models.Model):
    choices_type_company = (    ('MEI', 'MicroEmpreendedor Individual'),
                                ('ME', 'Microempresa'),
                                ('EPP', 'Empresa de Pequeno Porte'))
    choices_status = (  ('A', 'Ativo'),
                        ('I', 'Inativo'))
    type_company = models.CharField(max_length=3, choices=choices_type_company, default="MEI")
    status = models.CharField(max_length=1, choices=choices_status, default="A")
                            
    token_company = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=250)

    start_data = models.DateField()
    cnpj = models.CharField(max_length=20, blank=True)
    insc_est = models.CharField(max_length=20, blank=True)
    insc_mun = models.CharField(max_length=20, blank=True)

    street = models.CharField(max_length=100, blank=True)
    number = models.IntegerField(blank=True)
    complement = models.CharField(max_length=20, blank=True)
    district = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=2, blank=True)
    zipcode = models.CharField(max_length=15, blank=True)
    google_maps_link = models.TextField(blank=True)

    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=25, blank=True)
    whatsapp_number = models.CharField(max_length=25, blank=True)
    whatsapp_link = models.CharField(max_length=250, blank=True)

    site_link = models.CharField(max_length=250, blank=True)
    instagram_link = models.CharField(max_length=250, blank=True)
    linkedin_link = models.CharField(max_length=250, blank=True)
    facebook_link = models.CharField(max_length=250, blank=True)

    user_company = models.ForeignKey(User, blank=True, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class TokenUser(models.Model):
    token = models.CharField(max_length=64)
    active = models.BooleanField(default=False)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.user.username

activation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.messages import constants
from django.contrib.auth.decorators import login_required
from .models import Company
from django.contrib.auth.models import User
from django.contrib import auth
from django.conf import settings
import os
from .utils import password_is_valid, fields_empty, email_html
from .models import TokenUser, Company
from hashlib import sha256


sig = 'SIG SANLIS | '


## Database User
def register(request):
    title = 'Registrar'
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/auth/empresas')
        return render(request, 'user/user_register.html', {'title': title})

    elif request.method == "POST":
        cnpj = request.POST.get('cnpj')
        token_company = request.POST.get('token_company')
        companies = Company.objects.filter(cnpj=cnpj, token_company=token_company)
            
        if not companies.exists():
            messages.add_message(request, constants.ERROR, 'CNPJ e/ou Token Não Conferem !!!')
            return redirect('/auth/registrar/')

        company_id = companies[0].id     
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        users = User.objects.filter(username=username)

        if users.exists():
            messages.add_message(request, constants.ERROR, 'Existe um usuário cadastrado com este nome!!!')
            return redirect('/auth/registrar/')

        if not fields_empty(request, username, email):
            return redirect('/auth/registrar/')

        if not password_is_valid(request, password, confirm_password):
            return redirect('/auth/registrar')
        
        try:
            user = User.objects.create_user(    username=username,
                                                first_name=first_name,
                                                last_name=last_name,
                                                email=email,
                                                password=password,
                                                is_active=False)
            user.save()

            token = sha256(f'{username}{email}'.encode()).hexdigest()
            activation = TokenUser(token=token, user=user, company_id=company_id)
            activation.save()

            path_template = os.path.join(settings.BASE_DIR, 'activation/templates/user/active_account.html')
            email_html(path_template, 'Cadastro confirmado', [email,], username=username, link_activation=f"127.0.0.1:8000/auth/ativar_conta/{token}")
            
            messages.add_message(request, constants.SUCCESS, 'Usuário Cadastrado com Sucesso !!!')
            return redirect('/auth/login')
        except:
            messages.add_message(request, constants.DEBUG, 'Erro Interno do Sistema !!!')
            return redirect('/auth/registrar')


def login(request):
    title = 'Login'
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/auth/empresas')
        return render(request, 'user/user_login.html', {'title': title})
    elif request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_filter = User.objects.filter(username=username)

        if not user_filter.exists():
            messages.add_message(request, constants.ERROR, 'Usuário Não Existe !!!')
            return redirect('/auth/login/')

        user_active = User.objects.filter(username=username, is_active=False)

        if user_active.exists():
            messages.add_message(request, constants.ERROR, 'Usuário Não Ativado !!!')
            return redirect('/auth/login/')

        user_auth = auth.authenticate(username=username, password=password)

        if not user_auth:
            messages.add_message(request, constants.ERROR, 'Senha Inválida !!!')
            return redirect('/auth/login')
        else:
            auth.login(request, user_auth)
            return redirect('/painel')


@login_required(login_url='/auth/login/')
def logout(request):
    auth.logout(request)
    return redirect('/auth/login')


def active_account(request, token):
    token = get_object_or_404(TokenUser, token=token)
    if token.active:
        messages.add_message(request, constants.WARNING, 'Você já ativou sua conta!')
        return redirect('/auth/login')
    user = User.objects.get(username=token.user.username)
    user.is_active = True
    user.save()
    token.active = True
    token.save()
    messages.add_message(request, constants.SUCCESS, 'Conta Ativada com Sucesso!')
    return redirect('/auth/login')


## Database Company
@login_required(login_url='/auth/login/')
def companies(request):
    title = sig + 'Listar Empresas'

    users = User.objects.all()
    user_login = User.objects.filter(username=request.user)
    user_token_company = TokenUser.objects.filter(user_id=request.user).values('company_id')
    user_token_company_id = user_token_company.values_list('company_id')
    user_super = User.objects.filter(is_superuser=1, username=request.user)
    
    if user_super.exists():
        name_filtrar = request.GET.get('name')
        companies = Company.objects.all()

        if name_filtrar:
            companies = companies.filter(name__icontains = name_filtrar)
        context =   {   'title': title,
                        'users': users,
                        'user_login': user_login[0],
                        'companies': companies}
        render(request, 'company/company_list.html', context)

    else:
        user_token_company_id_value = user_token_company_id[0][0]
        name_filtrar = request.GET.get('name')
        companies = Company.objects.filter(id=user_token_company_id_value)

        if name_filtrar:
            companies = companies.filter(name__icontains = name_filtrar)
            
        context =   {   'title': title,
                        'users': users,
                        'user_login': user_login[0],
                        'companies': companies}
        render(request, 'company/company_list.html', context)

    return render(request, 'company/company_list.html', context)


@login_required(login_url='/auth/login/')
def company_create(request):
    title = sig + 'Criar Empresa'
    user_login = User.objects.filter(username=request.user)

    users = User.objects.all()
    context =   {   'title': title,
                    'user_login': user_login[0],
                    'users': users}
    if request.method == "GET":
        user_super = User.objects.filter(is_superuser=1, username=request.user)
    
        if user_super.exists():
            return render(request, 'company/company_create.html', context)
        else:
            messages.add_message(request, constants.ERROR, 'Seu usuário não tem acesso a incluir uma nova empresa!')
            return redirect('/auth/empresas')
    elif request.method == "POST":
        user_super = User.objects.filter(is_superuser=1, username=request.user)
    
        if user_super.exists():
            token_company = request.POST.get('token_company')
            name = request.POST.get('name').upper()
            full_name = request.POST.get('full_name').upper()

            start_data = request.POST.get('start_data')
            cnpj = request.POST.get('cnpj')
            insc_est = request.POST.get('insc_est')
            insc_mun = request.POST.get('insc_mun')

            street = request.POST.get('street').upper()
            number1 = request.POST.get('number')
            number = 0 if number1 == "" else request.POST.get('number')
            complement = request.POST.get('complement')
            district = request.POST.get('district').upper()
            city = request.POST.get('city').upper()
            state = request.POST.get('state').upper()
            zipcode = request.POST.get('zipcode')
            google_maps_link = request.POST.get('google_maps_link')

            email = request.POST.get('email').lower()
            phone = request.POST.get('phone')
            whatsapp_number = request.POST.get('whatsapp_number')
            whatsapp_link = request.POST.get('whatsapp_link').lower()

            site_link = request.POST.get('site_link').lower()
            instagram_link = request.POST.get('instagram_link').lower()
            linkedin_link = request.POST.get('linkedin_link').lower()
            facebook_link = request.POST.get('facebook_link').lower()

            user_company = request.POST.get('user_company')
            type_company = request.POST.get('type_company')

            if (len(name.strip()) == 0) or (len(full_name.strip()) == 0):
                messages.add_message(request, constants.ERROR, 'Preencha todos os campos!!!')
                return render(request, 'company/company_create.html', context)

            companies = Company.objects.filter(name=name)

            if companies.exists():
                messages.add_message(request, constants.ERROR, 'Já existe uma empresa cadastrada com este nome!!!')
                return render(request, 'company/company_create.html', context)

            try:
                company = Company(  token_company=token_company,
                                    name=name,
                                    full_name=full_name,

                                    start_data=start_data,
                                    cnpj=cnpj,
                                    insc_est=insc_est,
                                    insc_mun=insc_mun,

                                    street=street,
                                    number=number,

activation/templates/company/base.html
{% extends 'base_user.html' %}
{% load static  %}
{% block head %}
{% endblock %}

{% block container %}

{% endblock %}

activation/templates/company/breadcrumb.html
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'plataform:dashboard' %}">Painel</a></li>
        <li class="breadcrumb-item"><a href="{% url 'activation:companies' %}">Empresas</a></li>
        <li class="breadcrumb-item"><a href="{% url 'activation:companies' %}">Usuários</a></li>
    </ol>
</nav>

activation/templates/company/company_create.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'company/breadcrumb.html' %}

    <section class="row my-2">

        <div class="col-md-10">
            <h3 class="text-success">Criar Empresa</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'activation:companies' %}">
                <button type="button" class="btn btn-success btn-sm px-5">
                    <span class="fa fa-arrow-left"></span> Voltar
                </button>
            </a>
        </div>

    </section>

    <section class="container-fluid mb-5">

        {% include 'messages.html' %}

        <section class="row">

            <div class="col-md-12 border border-success py-2">

                <form action="{% url 'activation:company_create' %}" method="POST">
                    {% csrf_token %}

                    <div class="row mt-2">
                        <div class="col-sm-2">
                            <span>Token *</span>
                            <input type="text" placeholder="" class="form-control" name="token_company">
                        </div>
                        <div class="col-sm-3">
                            <span>Nome Fantasia *</span>
                            <input type="text" placeholder="" class="form-control" name="name">
                        </div>
                        <div class="col-sm-5">
                            <span>Razão Social *</span>
                            <input type="text" placeholder="" class="form-control" name="full_name">
                        </div>
                        <div class="col-sm-2">
                            <span>Usuário</span>
                            <select class="form-control" name="user_company">
                                {% for user in users %}
                                <option value="{{ user.id }}">{{ user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-2">
                            <span>Inicio Atividade</span>
                            <input type="date" placeholder="" class="form-control" name="start_data">
                        </div>
                        <div class="col-sm-3">
                            <span>CNPJ</span>
                            <input type="text" placeholder="" class="form-control" name="cnpj">
                        </div>
                        <div class="col-sm-2">
                            <span>Insc.Est.</span>
                            <input type="text" placeholder="" class="form-control" name="insc_est">
                        </div>
                        <div class="col-sm-2">
                            <span>Insc.Mun.</span>
                            <input type="text" placeholder="" class="form-control" name="insc_mun">
                        </div>
                        <div class="col-sm-3">
                            <span>Tipo Empresa</span>
                            <select class="form-control" name="type_company">
                                <option value="MEI">Micro Empreendedor Individual</option>
                                <option value="ME">Microempresa</option>
                                <option value="EPP">Empresa de Pequeno Porte</option>
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-5">
                            <span>Endereço</span>
                            <input type="text" placeholder="" class="form-control" name="street">
                        </div>
                        <div class="col-sm-2">
                            <span>Numero</span>
                            <input type="text" placeholder="" class="form-control" name="number">
                        </div>
                        <div class="col-sm-2">
                            <span>Complemento</span>
                            <input type="text" placeholder="" class="form-control" name="complement">
                        </div>
                        <div class="col-sm-3">
                            <span>Bairro</span>
                            <input type="text" placeholder="" class="form-control" name="district">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-4">
                            <span>Cidade</span>
                            <input type="text" placeholder="" class="form-control" name="city">
                        </div>
                        <div class="col-sm-1">
                            <span>UF</span>
                            <input type="text" placeholder="" class="form-control" name="state">
                        </div>
                        <div class="col-sm-2">
                            <span>CEP</span>
                            <input type="text" placeholder="" class="form-control" name="zipcode">
                        </div>
                        <div class="col-sm-5">
                            <span>Google Maps Link:</span>
                            <input type="text" placeholder="" class="form-control" name="google_maps_link">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-4">
                            <span>Email</span>
                            <input type="email" placeholder="" class="form-control" name="email">
                        </div>
                        <div class="col-sm-2">
                            <span>Telefone 1</span>
                            <input type="text" placeholder="" class="form-control" name="phone">
                        </div>
                        <div class="col-sm-2">
                            <span>Telefone 2</span>
                            <input type="text" placeholder="" class="form-control" name="whatsapp_number">
                        </div>
                        <div class="col-sm-4">
                            <span>Whatsapp Link</span>
                            <input type="text" placeholder="" class="form-control" name="whatsapp_link">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-3">
                            <span>Site</span>
                            <input type="text" placeholder="" class="form-control" name="site_link">
                        </div>
                        <div class="col-sm-3">
                            <span>Instagram</span>
                            <input type="text" placeholder="" class="form-control" name="instagram_link">
                        </div>
                        <div class="col-sm-3">
                            <span>Linkedin</span>
                            <input type="text" placeholder="" class="form-control" name="linkedin_link">
                        </div>
                        <div class="col-sm-3">
                            <span>Facebook</span>
                            <input type="text" placeholder="" class="form-control" name="facebook_link">
                        </div>
                    </div>

                    <div class="row my-3">
                        <div class="col-sm-10">
                            <h6>* Token, Nome Fantasia e Razão Social não podem ficar vazios.</h6>
                        </div>
                        <div class="col-sm-2">
                            <input type="submit" class="btn btn-success btn-sm px-5" value="Cadastrar">
                        </div>
                    </div>

                </form>

            </div>

        </section>

    </section>

</main>

{% endblock%}

activation/templates/company/company_list.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'company/breadcrumb.html' %}

    {% include 'messages.html' %}

    <section class="row">

        <div class="col-md-10">
            <h3 class="text-success">Gerenciar Empresas</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'activation:company_create' %}">
                <button type="button" class="btn btn-success btn-sm px-2">
                    <span class="fa fa-plus"></span> Nova Empresa
                </button>
            </a>
        </div>

    </section>

    <section class="body-box">

        <form action="{% url 'activation:companies' %}" method="GET">
            {% csrf_token %}
            <div class="row">
                
                <section class="col-md-5 mb-2">
                    <input type="text" placeholder="Buscar pelo Nome" class="form-control" name="name">
                </section>
                
                <section class="col-md-2">
                    <input type="submit" value="FILTRAR" class="btn btn-success px-5">
                </section>

            </div>
        </form>

        <table class="table table-sm table-responsive-sm table-hover mt-2">

            <thead class="thead-dark">
                <tr>
                    <th>Nome Fantasia</th>
                    <th>Token</th>
                    <th>Phone1</th>
                    <th>Phone2</th>
                    <th>CNPJ</th>
                    <th>Inicio Atividade</th>
                    <th>Usuário Main</th>
                    <th>Excluir</th>
                </tr>
            </thead>

            <tbody class="table-group-divider">
                {% for company in companies %}
                <tr class="tabela-linha">
                    <td><a href="{% url 'activation:company_view' company.id %}">{{ company.name }}</a></td>
                    <td>{{ company.token_company }}</td>
                    <td>{{ company.phone }}</td>
                    <td>{{ company.whatsapp_number }}</td>
                    <td>{{ company.cnpj }}</td>
                    <td>{{ company.start_data|date:"d/m/Y"|default:'---' }}</td>
                    <td>               
                        <span value="{{ company.user_id }}">{{ company.user_company }}</span> 
                    </td>
                    <td><a class="btn-sm btn-danger" href="{% url 'activation:company_delete' company.id %}"
                        onclick="return confirm('Você tem certeza que deseja excluir esta empresa ?')">
                        <i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
        
    </section>

</main>

{% endblock %}