home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre/', views.about, name='about'),
    path('contato/', views.contact, name='contact'),
]

plataform/urls.py
from django.urls import path, include
from . import views

app_name = 'plataform'


partners_patterns = [
    path('', views.partners, name='partners'),
    path('novo_parceiro/', views.partner_create, name='partner_create'),
    path('visualizar_parceiro/<int:id>', views.partner_view, name="partner_view"),
    path('alterar_parceiro/<int:id>', views.partner_update, name="partner_update"),
    path('excluir_parceiro/<int:id>', views.partner_delete, name="partner_delete"),
]

items_patterns = [
    path('', views.items, name='items'),
    path('novo_item/', views.item_create, name='item_create'),
    path('visualizar_item/<int:id>', views.item_view, name="item_view"),
    path('alterar_item/<int:id>', views.item_update, name="item_update"),
    path('excluir_item/<int:id>', views.item_delete, name="item_delete"),
    
    # Ajax para Saldo
    path('<int:pk>/json/', views.produto_json, name='produto_json'),

    path('nova_un_med/', views.un_med_create, name='un_med_create'),
    path('nova_categoria/', views.category_create, name='category_create'),
]

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('parceiros/', include(partners_patterns)),
    path('itens/', include(items_patterns)),
]

sig_sanlis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('activation.urls')),
    path('', include('home.urls')),
    path('painel/', include('plataform.urls')),
    path('painel/estoque/', include('stock.urls')),
]

plataform/models.py
from django.db import models
from home.models import TimeStampedModel

from activation.models import Company
from django.utils import timezone


class PartnerGroup(models.Model):
    group = models.CharField(max_length=30)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('group',)

    def __str__(self):
        return self.group


class PartnerSubGroup(models.Model):
    subgroup = models.CharField(max_length=30)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('subgroup',)

    def __str__(self):
        return self.subgroup


class Partner(TimeStampedModel):
    choices_type_partners = (   ('1', 'Cliente'),
                                ('2', 'Fornecedor'),
                                ('3', 'Transportadora'),
                                ('4', 'Vendedor'),
                                ('5', 'Funcionário'))
    choices_gender = (  ('F', 'Feminino'),
                        ('M', 'Masculino'))
    choices_type_person = ( ('F', 'Física'),
                            ('J', 'Jurídica'))
    choices_status = (  ('A', 'Ativo'),
                        ('I', 'Inativo'))

    nickname = models.CharField(max_length=20)
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    document = models.CharField(max_length=30, null=True)
    email = models.EmailField(null=True)
    phone1 = models.CharField(max_length=20, null=True)
    phone2 = models.CharField(max_length=20, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    address = models.CharField(max_length=100, null=True)
    number = models.CharField(max_length=10, null=True)
    compl = models.CharField(max_length=20, null=True)
    district = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=30, null=True)
    country = models.CharField(max_length=30, null=True)
    zipcode = models.CharField(max_length=20, null=True)

    cnpj = models.CharField(max_length=30, null=True)
    insc_est = models.CharField(max_length=30, null=True)
    insc_mun = models.CharField(max_length=30, null=True)
    rg = models.CharField(max_length=30, null=True)
    cpf = models.CharField(max_length=30, null=True)
    tit_eleitor = models.CharField(max_length=30, null=True)
    zona = models.CharField(max_length=10, null=True)
    secao = models.CharField(max_length=10, null=True)
    ctps = models.CharField(max_length=30, null=True)
    pis = models.CharField(max_length=30, null=True)
    cert_reservista = models.CharField(max_length=30, null=True)
    cnh = models.CharField(max_length=30, null=True)

    data_nasc = models.DateField(default=timezone.now)
    data_admissao = models.DateField(default=timezone.now)
    data_demissao = models.DateField(default=timezone.now)

    banco = models.CharField(max_length=30, null=True)
    agencia = models.CharField(max_length=30, null=True)
    tipo_conta = models.CharField(max_length=30, null=True)
    conta = models.CharField(max_length=30, null=True)
    pix = models.CharField(max_length=30, null=True)

    group = models.ForeignKey(PartnerGroup, on_delete=models.CASCADE, null=True, blank=True, default=None)
    subgroup = models.ForeignKey(PartnerSubGroup, on_delete=models.CASCADE, null=True, blank=True, default=None)
    
    type_partners = models.CharField(max_length=1, choices=choices_type_partners, default="1")
    type_person = models.CharField(max_length=1, choices=choices_type_person, default="J")
    gender = models.CharField(max_length=1, choices=choices_gender, default="M")
    status = models.CharField(max_length=1, choices=choices_status, default="A")

    class Meta:
        ordering = ('nickname',)

    def __str__(self):
        return self.nickname


class Category(models.Model):
    category = models.CharField(max_length=30)
    markup = models.FloatField(null=True)
    commission = models.FloatField(null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('category',)

    def __str__(self):
        return self.category


class UnMed(models.Model):
    un_med = models.CharField(max_length=5)
    description = models.CharField(max_length=30)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('description',)

    def __str__(self):
        return self.un_med


class Brand(models.Model):
    brand = models.CharField(max_length=30)
    markup = models.FloatField(null=True)
    commission = models.FloatField(null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('brand',)

    def __str__(self):
        return self.brand


class Item(TimeStampedModel):
    choices_status = (  ('A', 'Ativo'),
                        ('I', 'Inativo'))
    choices_type_item = (   ('1', 'Produto para Revenda'),
                            ('2', 'Produção Própria'),
                            ('3', 'Serviço Prestado'),
                            ('4', 'Matéria-Prima'),
                            ('5', 'Consumo e Utilização'),
                            ('6', 'Ativo Patrimonial'))
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250, null=True)
    location = models.CharField(max_length=20, null=True)
    reference = models.CharField(max_length=20, null=True)

    price_in_cash = models.FloatField(null=True)
    price_term = models.FloatField(null=True)
    price_promotion = models.FloatField(null=True)
    price_custom = models.FloatField(null=True)

    stock_qtd = models.FloatField(null=True)
    stock_control = models.BooleanField()

    stock_min = models.FloatField(null=True)
    stock_max = models.FloatField(null=True)
    stock_seg = models.FloatField(null=True)
    lot_min = models.FloatField(null=True)
    lot_mult = models.FloatField(null=True)
    lead_time = models.FloatField(null=True)

    code_ean = models.CharField(max_length=20, null=True)
    code_dun = models.CharField(max_length=20, null=True)
    code_fab = models.CharField(max_length=20, null=True)

    length = models.FloatField(null=True)
    height = models.FloatField(null=True)
    width = models.FloatField(null=True)
    weight_gross = models.FloatField(null=True)
    weight_net = models.FloatField(null=True)

    pack_master = models.FloatField(null=True)
    pack_sale = models.FloatField(null=True)

    ncm = models.CharField(max_length=20, null=True)
    cst = models.CharField(max_length=20, null=True)

    color = models.CharField(max_length=20, null=True)
    size = models.CharField(max_length=20, null=True)
    material = models.CharField(max_length=20, null=True)

    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=choices_status, default="A")
    type_item = models.CharField(max_length=1, choices=choices_type_item, default="S")
    un_med = models.ForeignKey(UnMed, on_delete=models.CASCADE, null=True, blank=True, default=None)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, default=None)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True, default=None)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title
    
    # Ajax para Saldo
    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.title,
            'estoque': self.stock_qtd,
        }

plataform/templates/partners/partner_create.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'breadcrumb.html' %}

    <section class="row my-2">

        <div class="col-md-10">
            <h3 class="text-success">Criar Parceiro</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'plataform:partners' %}">
                <button type="button" class="btn btn-success btn-sm px-5">
                    <span class="fa fa-arrow-left"></span> Voltar
                </button>
            </a>
        </div>

    </section>

    <section class="container-fluid mb-3">

        {% include 'messages.html' %}
        
        <section class="row">

            <div class="col-md-12 border border-success py-2">

                <form action="{% url 'plataform:partner_create' %}" method="POST">
                    {% csrf_token %}

                    <input type="hidden" class="form-control" name="company" value="{{ company_id_value }}">

                    <div class="row">
                        <div class="col-sm-6">
                            <span>Apelido *</span>
                            <input type="text" class="form-control" name="nickname">
                        </div>
                        <div class="col-sm-6">
                            <span>Documento *</span>
                            <input type="text" class="form-control" name="document">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-6">
                            <span>Nome</span>
                            <input type="text" class="form-control" name="first_name">
                        </div>
                        <div class="col-sm-6">
                            <span>Sobrenome</span>
                            <input type="text" class="form-control" name="last_name">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-6">
                            <span>Telefone 1</span>
                            <input type="text" class="form-control" name="phone1">
                        </div>
                        <div class="col-sm-6">
                            <span>Telefone 2</span>
                            <input type="text" class="form-control" name="phone2">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-12">
                            <span class="mt-2">E-mail</span>
                            <input type="email" class="form-control" name="email">
                        </div>
                    </div>  

                    <div class="row mt-2">
                        <div class="col-sm-2">
                            <span>Tipo Parceiro</span>
                            <select name="type_partners" class="form-control">
                                <option value="1">Cliente</option>
                                <option value="2">Fornecedor</option>
                                <option value="3">Transportadora</option>
                                <option value="4">Vendedor</option>
                                <option value="5">Funcionário</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Tipo Pessoa</span>
                            <select name="type_person" class="form-control">
                                <option value="F">Física</option>
                                <option value="J">Jurídica</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Sexo</span>
                            <select name="gender" class="form-control">
                                <option value="M">Masculino</option>
                                <option value="F">Feminino</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <span>Grupo</span>
                            <select name="group" class="form-control">
                                <option value="">Sem Grupo</option> 
                                {% for group in groups %}
                                    <option value="{{ group.id }}">{{ group.group }}</option> 
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <span>SubGrupo</span>
                            <select name="subgroup" class="form-control">
                                <option value="">Sem SubGrupo</option> 
                                {% for subgroup in subgroups %}
                                    <option value="{{ subgroup.id }}">{{ subgroup.subgroup }}</option> 
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row my-3">
                        <div class="col-sm-10">
                            <h6>* Os campos Apelido e Documento não podem ficar vazios.</h6>
                        </div>
                        <div class="col-sm-2">
                            <input type="submit" class="btn btn-success btn-sm px-5" value="Cadastrar">
                        </div>
                    </div>

                </form>

            </div>
            
        </section>
        
    </section>
    
</main>

{% endblock %}

plataform/templates/partners/partner_list.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'breadcrumb.html' %}

    {% include 'messages.html' %}

    <section class="row my-2">

        <div class="col-md-10">
            <h3 class="text-success">Gerenciar Parceiros</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'plataform:partner_create' %}">
                <button type="button" class="btn btn-success btn-sm px-5">
                    <span class="fa fa-plus"></span> Adicionar
                </button>
            </a>
        </div>

    </section>

    <section class="body-box">

        <form action="{% url 'plataform:partners' %}" method="GET">
            {% csrf_token %}
            <div class="row">
                
                <section class="col-md-5 mb-2">
                    <input type="text" placeholder="Buscar pelo Apelido" class="form-control" name="nickname">
                </section>

                <section class="col-md-2 mb-2">
                    <select class="form-control" name="groups">
                        <option value="">Escolha Grupo</option>
                        {% for group in groups %}
                        <option value="{{ group.id }}">{{ group }}</option>
                        {% endfor %}
                    </select>
                </section>

                <section class="col-md-2 mb-2">
                    <select class="form-control" name="subgroups">
                        <option value="">Escolha SubGrupo</option>
                        {% for subgroup in subgroups %}
                        <option value="{{ subgroup.id }}">{{ subgroup }}</option>
                        {% endfor %}
                    </select>
                </section>
                
                <section class="col-md-2">
                    <input type="submit" value="FILTRAR" class="btn btn-outline-success px-5">
                </section>

            </div>
        </form>

        <table class="table table-sm table-responsive-sm table-hover mt-2">

            <thead class="thead-dark">
                <tr>
                    <th>Status</th>
                    <th>Apelido</th>
                    <th>Phone1</th>
                    <th>Phone2</th>
                    <th>Documento</th>
                    <th>Nome</th>
                    <th>Sobrenome</th>
                    <th>Email</th>
                    <th>Editar</th>
                    <th>Deletar</th>
                </tr>
            </thead>

            <tbody class="table-group-divider">
                {% for partner in page.object_list %}
                <tr class="tabela-linha">
                    <td>
                        {% if partner.status == 'A' %}
                            <i class="fa fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fa fa-minus-circle text-danger"></i>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'plataform:partner_view' partner.id %}">{{ partner.nickname }}</a></td>
                    <td>{{ partner.phone1 }}</td>
                    <td>{{ partner.phone2 }}</td>
                    <td>{{ partner.document }}</td>
                    <td>{{ partner.first_name }}</td>
                    <td>{{ partner.last_name }}</td>
                    <td>{{ partner.email }}</td>
                    <td><a class="btn-sm btn-warning" href="{% url 'plataform:partner_view' partner.id %}">
                        <i class="fa fa-edit"></i></a>
                    </td>
                    <td><a class="btn-sm btn-danger" href="{% url 'plataform:partner_delete' partner.id %}"
                        onclick="return confirm('Você tem certeza que deseja excluir este parceito ?')">
                        <i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>

        {% include 'pagination.html' %}
        
    </section>

</main>

{% endblock %}

plataform/templates/partners/partner_update.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'breadcrumb.html' %}

    <section class="row my-2">

        <div class="col-md-10">
            <h3 class="text-success">Alterar Parceiro</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'plataform:partners' %}">
                <button type="button" class="btn btn-success btn-sm px-5">
                    <span class="fa fa-arrow-left"></span> Voltar
                </button>
            </a>
        </div>

    </section>

    <section class="container-fluid mb-3">

        {% include 'messages.html' %}
        
        <section class="row">

            <div class="col-md-12 border border-success py-2">

                <form action="{% url 'plataform:partner_update' partner.id %}" method="POST">
                    {% csrf_token %}

                    <input type="hidden" class="form-control" name="company" value="{{ company_id_value }}">

                    <div class="row">
                        <div class="col-sm-1">
                            <span>ID</span>
                            <input type="text" value="{{ partner.id }}" class="form-control" disabled name="id">
                        </div>
                        <div class="col-sm-5">
                            <span>Apelido *</span>
                            <input type="text" value="{{ partner.nickname }}" class="form-control" name="nickname">
                        </div>
                        <div class="col-sm-4">
                            <span>Documento *</span>
                            <input type="text" value="{{ partner.document }}" class="form-control" name="document">
                        </div>
                        <div class="col-sm-2">
                            <span>Status</span>
                            <select name="status" class="form-control">
                                <option value="{{ partner.status }}">{{ partner.get_status_display }}</option>
                                <option disabled value=""> . Escolha uma Opção</option>
                                <option value="A">Ativo</option>
                                <option value="I">Inativo</option>
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-6">
                            <span>Nome</span>
                            <input type="text" value="{{ partner.first_name }}" class="form-control" name="first_name">
                        </div>
                        <div class="col-sm-6">
                            <span>Sobrenome</span>
                            <input type="text" value="{{ partner.last_name }}" class="form-control" name="last_name">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-6">
                            <span>Telefone 1</span>
                            <input type="text" value="{{ partner.phone1 }}" class="form-control" name="phone1">
                        </div>
                        <div class="col-sm-6">
                            <span>Telefone 2</span>
                            <input type="text" value="{{ partner.phone2 }}" class="form-control" name="phone2">
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-12">
                            <span class="mt-2">E-mail</span>
                            <input type="email" value="{{ partner.email }}" class="form-control" name="email">
                        </div>
                    </div>  

                    <div class="row mt-2">
                        <div class="col-sm-2">
                            <span>Tipo Parceiro</span>
                            <select name="type_partners" class="form-control">
                                <option value="{{ partner.type_partners }}">{{ partner.get_type_partners_display }}</option>
                                <option disabled value=""> . Escolha um Tipo</option>
                                <option value="1">Cliente</option>
                                <option value="2">Fornecedor</option>
                                <option value="3">Transportadora</option>
                                <option value="4">Vendedor</option>
                                <option value="5">Funcionário</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Tipo Pessoa</span>
                            <select name="type_person" class="form-control">
                                <option value="{{ partner.type_person }}">{{ partner.get_type_person_display }}</option>
                                <option disabled value=""> . Escolha um Tipo</option>
                                <option value="F">Física</option>
                                <option value="J">Jurídica</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Sexo</span>
                            <select name="gender" class="form-control">
                                <option value="{{ partner.gender }}">{{ partner.get_gender_display }}</option>
                                <option disabled value=""> . Escolha uma Opção</option>
                                <option value="M">Masculino</option>
                                <option value="F">Feminino</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <span>Grupo</span>
                            <select name="group" class="form-control">
                                {% if partner.group_id == None %}
                                    <option value="">Sem Grupo</option>
                                {% else %}
                                    <option value="{{ partner.group_id }}">
                                        {{ partner.group }}
                                    </option>
                                {% endif %}
                                <option disabled value=""> >>> Escolha um Grupo</option>
                                {% for group in groups %}
                                    <option value="{{ group.id }}">{{ group }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <span>SubGrupo</span>
                            <select name="subgroup" class="form-control">
                                {% if partner.subgroup_id == None %}
                                    <option value="">Sem SubGrupo</option>
                                {% else %}
                                    <option value="{{ partner.subgroup_id }}">
                                        {{ partner.subgroup }}
                                    </option>
                                {% endif %}
                                <option disabled value=""> >>> Escolha um SubGrupo</option>
                                {% for subgroup in subgroups %}
                                    <option value="{{ subgroup.id }}">{{ subgroup }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row my-3">
                        <div class="col-sm-10">
                            <h6>* Os campos Apelido e Documento não podem ficar vazios.</h6>
                        </div>
                        <div class="col-sm-2">
                            <input type="submit" class="btn btn-success btn-sm px-5" value="Alterar">
                        </div>
                    </div>
                    
                </form>

            </div>
            
        </section>
        
    </section>
    
</main>

{% endblock %}