home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('sobre/', views.about, name='about'),
    path('contato/', views.contact, name='contact'),
]

plataform/urls.py
from django.urls import path, include
from . import views

app_name = 'plataform'


partners_patterns = [
    path('', views.partners, name='partners'),
    path('novo_parceiro/', views.partner_create, name='partner_create'),
    path('visualizar_parceiro/<int:id>', views.partner_view, name="partner_view"),
    path('alterar_parceiro/<int:id>', views.partner_update, name="partner_update"),
    path('excluir_parceiro/<int:id>', views.partner_delete, name="partner_delete"),
]

items_patterns = [
    path('', views.items, name='items'),
    path('novo_item/', views.item_create, name='item_create'),
    path('visualizar_item/<int:id>', views.item_view, name="item_view"),
    path('alterar_item/<int:id>', views.item_update, name="item_update"),
    path('excluir_item/<int:id>', views.item_delete, name="item_delete"),
    
    # Ajax para Saldo
    path('<int:pk>/json/', views.produto_json, name='produto_json'),

    path('nova_un_med/', views.un_med_create, name='un_med_create'),
    path('nova_categoria/', views.category_create, name='category_create'),
]

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('parceiros/', include(partners_patterns)),
    path('itens/', include(items_patterns)),
]

sig_sanlis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('activation.urls')),
    path('', include('home.urls')),
    path('painel/', include('plataform.urls')),
    path('painel/estoque/', include('stock.urls')),
]

plataform/models.py
from django.db import models
from home.models import TimeStampedModel

from activation.models import Company
from django.utils import timezone


class PartnerGroup(models.Model):
    group = models.CharField(max_length=30)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('group',)

    def __str__(self):
        return self.group


class PartnerSubGroup(models.Model):
    subgroup = models.CharField(max_length=30)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('subgroup',)

    def __str__(self):
        return self.subgroup


class Partner(TimeStampedModel):
    choices_type_partners = (   ('1', 'Cliente'),
                                ('2', 'Fornecedor'),
                                ('3', 'Transportadora'),
                                ('4', 'Vendedor'),
                                ('5', 'Funcionário'))
    choices_gender = (  ('F', 'Feminino'),
                        ('M', 'Masculino'))
    choices_type_person = ( ('F', 'Física'),
                            ('J', 'Jurídica'))
    choices_status = (  ('A', 'Ativo'),
                        ('I', 'Inativo'))

    nickname = models.CharField(max_length=20)
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    document = models.CharField(max_length=30, null=True)
    email = models.EmailField(null=True)
    phone1 = models.CharField(max_length=20, null=True)
    phone2 = models.CharField(max_length=20, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    address = models.CharField(max_length=100, null=True)
    number = models.CharField(max_length=10, null=True)
    compl = models.CharField(max_length=20, null=True)
    district = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=30, null=True)
    country = models.CharField(max_length=30, null=True)
    zipcode = models.CharField(max_length=20, null=True)

    cnpj = models.CharField(max_length=30, null=True)
    insc_est = models.CharField(max_length=30, null=True)
    insc_mun = models.CharField(max_length=30, null=True)
    rg = models.CharField(max_length=30, null=True)
    cpf = models.CharField(max_length=30, null=True)
    tit_eleitor = models.CharField(max_length=30, null=True)
    zona = models.CharField(max_length=10, null=True)
    secao = models.CharField(max_length=10, null=True)
    ctps = models.CharField(max_length=30, null=True)
    pis = models.CharField(max_length=30, null=True)
    cert_reservista = models.CharField(max_length=30, null=True)
    cnh = models.CharField(max_length=30, null=True)

    data_nasc = models.DateField(default=timezone.now)
    data_admissao = models.DateField(default=timezone.now)
    data_demissao = models.DateField(default=timezone.now)

    banco = models.CharField(max_length=30, null=True)
    agencia = models.CharField(max_length=30, null=True)
    tipo_conta = models.CharField(max_length=30, null=True)
    conta = models.CharField(max_length=30, null=True)
    pix = models.CharField(max_length=30, null=True)

    group = models.ForeignKey(PartnerGroup, on_delete=models.CASCADE, null=True, blank=True, default=None)
    subgroup = models.ForeignKey(PartnerSubGroup, on_delete=models.CASCADE, null=True, blank=True, default=None)
    
    type_partners = models.CharField(max_length=1, choices=choices_type_partners, default="1")
    type_person = models.CharField(max_length=1, choices=choices_type_person, default="J")
    gender = models.CharField(max_length=1, choices=choices_gender, default="M")
    status = models.CharField(max_length=1, choices=choices_status, default="A")

    class Meta:
        ordering = ('nickname',)

    def __str__(self):
        return self.nickname


class Category(models.Model):
    category = models.CharField(max_length=30)
    markup = models.FloatField(null=True)
    commission = models.FloatField(null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('category',)

    def __str__(self):
        return self.category


class UnMed(models.Model):
    un_med = models.CharField(max_length=5)
    description = models.CharField(max_length=30)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('description',)

    def __str__(self):
        return self.un_med


class Brand(models.Model):
    brand = models.CharField(max_length=30)
    markup = models.FloatField(null=True)
    commission = models.FloatField(null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('brand',)

    def __str__(self):
        return self.brand


class Item(TimeStampedModel):
    choices_status = (  ('A', 'Ativo'),
                        ('I', 'Inativo'))
    choices_type_item = (   ('1', 'Produto para Revenda'),
                            ('2', 'Produção Própria'),
                            ('3', 'Serviço Prestado'),
                            ('4', 'Matéria-Prima'),
                            ('5', 'Consumo e Utilização'),
                            ('6', 'Ativo Patrimonial'))
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250, null=True)
    location = models.CharField(max_length=20, null=True)
    reference = models.CharField(max_length=20, null=True)

    price_in_cash = models.FloatField(null=True)
    price_term = models.FloatField(null=True)
    price_promotion = models.FloatField(null=True)
    price_custom = models.FloatField(null=True)

    stock_qtd = models.FloatField(null=True)
    stock_control = models.BooleanField()

    stock_min = models.FloatField(null=True)
    stock_max = models.FloatField(null=True)
    stock_seg = models.FloatField(null=True)
    lot_min = models.FloatField(null=True)
    lot_mult = models.FloatField(null=True)
    lead_time = models.FloatField(null=True)

    code_ean = models.CharField(max_length=20, null=True)
    code_dun = models.CharField(max_length=20, null=True)
    code_fab = models.CharField(max_length=20, null=True)

    length = models.FloatField(null=True)
    height = models.FloatField(null=True)
    width = models.FloatField(null=True)
    weight_gross = models.FloatField(null=True)
    weight_net = models.FloatField(null=True)

    pack_master = models.FloatField(null=True)
    pack_sale = models.FloatField(null=True)

    ncm = models.CharField(max_length=20, null=True)
    cst = models.CharField(max_length=20, null=True)

    color = models.CharField(max_length=20, null=True)
    size = models.CharField(max_length=20, null=True)
    material = models.CharField(max_length=20, null=True)

    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=choices_status, default="A")
    type_item = models.CharField(max_length=1, choices=choices_type_item, default="S")
    un_med = models.ForeignKey(UnMed, on_delete=models.CASCADE, null=True, blank=True, default=None)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, default=None)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True, default=None)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title
    
    # Ajax para Saldo
    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.title,
            'estoque': self.stock_qtd,
        }

plataform/templates/items/item_create.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'breadcrumb.html' %}

    <section class="row my-2">

        <div class="col-md-10">
            <h3 class="text-success">Criar Item</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'plataform:items' %}">
                <button type="button" class="btn btn-success btn-sm px-5">
                    <span class="fa fa-arrow-left"></span> Voltar
                </button>
            </a>
        </div>

    </section>
    
    <section class="container-fluid mb-3">

        {% include 'messages.html' %}

        <section class="row">

            <div class="col-md-12 border border-success py-2">

                <form action="{% url 'plataform:item_create' %}" method="POST">
                    {% csrf_token %}

                    <input type="hidden" class="form-control" name="company" value="{{ company_id_value }}">

                    <div class="row">
                        <div class="col-sm-6">
                            <span>Nome *</span>
                            <input type="text" class="form-control" name="title">
                        </div>
                        <div class="col-sm-2">
                            <span>Referencia</span>
                            <input type="text" class="form-control" name="reference">
                        </div>
                        <div class="col-sm-2">
                            <span>Local</span>
                            <input type="text" class="form-control" name="location">
                        </div>
                        <div class="col-sm-2">
                            <span>Un Med</span>
                            <select name="un_med" class="form-control">
                                <option value="">Sem UnMed</option> 
                                {% for un_med in un_meds %} 
                                    <option value="{{ un_med.id }}">{{ un_med.description }}</option> 
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-3">
                            <span>Tipo Item</span>
                            <select name="type_item" class="form-control">
                                <option value="1">Produto para Revenda</option>
                                <option value="2">Produção Própria</option>
                                <option value="3">Serviço Prestado</option>
                                <option value="4">Matéria-Prima</option>
                                <option value="5">Consumo e Utilização</option>
                                <option value="6">Ativo Patrimonial</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Controla Estoque</span>
                            <select name="stock_control" class="form-control">
                                <option value="0">Não</option>
                                <option value="1">Sim</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Saldo Inicial</span>
                            <input type="number" step="0.01"
                                class="form-control" name="stock_qtd">
                        </div>
                        <div class="col-sm-2">
                            <span>Custo</span>
                            <input type="number" step="0.01"
                                class="form-control" name="price_custom">
                        </div>
                        <div class="col-sm-3">
                            <span>Marca</span>
                            <select name="brand" class="form-control">
                                <option value="">Sem Marca</option> 
                                {% for brand in brands %} 
                                    <option value="{{ brand.id }}">{{ brand.brand }}</option> 
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-2">
                            <span>Preço A Vista</span>
                            <input type="number" step="0.01"
                                class="form-control" name="price_in_cash">
                        </div>
                        <div class="col-sm-2">
                            <span>Preço A Prazo</span>
                            <input type="number" step="0.01"
                                class="form-control" name="price_term">
                        </div>
                        <div class="col-sm-2">
                            <span>Preço Promoção</span>
                            <input type="number" step="0.01"
                                class="form-control" name="price_promotion">
                        </div>
                        <div class="col-sm-6">
                            <span>Categoria</span>
                            <select name="category" class="form-control">
                                <option value="">Sem Categoria</option> 
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.category }}</option> 
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-12">
                            <span>Descrição</span>
                            <input type="text" class="form-control" name="description">
                        </div>
                    </div>  

                    <div class="row my-3">
                        <div class="col-sm-10">
                            <h6>* O campo Nome não pode fica vazio.</h6>
                        </div>
                        <div class="col-sm-2">
                            <input type="submit" class="btn btn-success btn-sm px-5" value="Cadastrar">
                        </div>
                    </div>

                </form>

            </div>

        </section>
        
    </section>
    
</main>

{% endblock %}

plataform/templates/items/item_list.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'breadcrumb.html' %}

    {% include 'messages.html' %}

    <section class="row my-2">

        <div class="col-md-10">
            <h3 class="text-success">Gerenciar Itens</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'plataform:item_create' %}">
                <button type="button" class="btn btn-success btn-sm px-5">
                    <span class="fa fa-plus"></span> Adicionar
                </button>
            </a>
        </div>

    </section>

    <section class="body-box">

        <form action="{% url 'plataform:items' %}" method="GET">
            {% csrf_token %}
            <div class="row">
                
                <section class="col-md-4 mb-2">
                    <input type="text" placeholder="Buscar pelo Nome" class="form-control" name="title">
                </section>

                <section class="col-md-3 mb-2">
                    <select class="form-control" name="categories">
                        <option value="">Escolha uma Categoria</option>
                        {% for category in categories %}
                        <option value="{{ category.id }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </section>

                <section class="col-md-2 mb-2">
                    <select class="form-control" name="brands">
                        <option value="">Escolha uma Marca</option>
                        {% for brand in brands %}
                        <option value="{{ brand.id }}">{{ brand }}</option>
                        {% endfor %}
                    </select>
                </section>
                
                <section class="col-md-1">
                    <input type="submit" value="FILTRAR" class="btn btn-outline-success px-5">
                </section>

            </div>
        </form>

        <table class="table table-sm table-responsive-sm table-hover mt-2">

            <thead class="thead-dark">
                <tr>
                    <th style="width:30px">Status</th>
                    <th style="width:200px">Nome</th>
                    <th style="width:100px" class="text-right">Estoque</th>
                    <th style="width:30px" class="text-center">UnMed</th>
                    <th style="width:100px" class="text-center">Ref</th>
                    <th style="width:100px" class="text-center">Localização</th>
                    <th style="width:70px" class="text-right">Preço</th>
                    <th style="width:70px" class="text-right">Custo</th>
                    <th style="width:30px" class="text-center">Editar</th>
                    <th style="width:30px" class="text-center">Deletar</th>
                </tr>
            </thead>

            <tbody class="table-group-divider">
                {% for item in page.object_list %}
                <tr class="tabela-linha">
                    <td style="width:30px">
                        {% if item.status == 'A' %}
                            <i class="fa fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fa fa-minus-circle text-danger"></i>
                        {% endif %}
                    </td>
                    <td style="width:200px"><a href="{% url 'plataform:item_view' item.id %}">{{ item.title }}</a></td>
                    <td style="width:100px" class="text-right">{{ item.stock_qtd|floatformat:3 }}</td>
                    <td style="width:30px" class="text-center">{{ item.un_med.description }}</td>
                    <td style="width:100px" class="text-center">{{ item.reference }}</td>
                    <td style="width:100px" class="text-center">{{ item.location }}</td>
                    <td style="width:70px" class="text-right">{{ item.price_term|floatformat:2 }}</td>
                    <td style="width:70px" class="text-right">{{ item.price_custom|floatformat:2 }}</td>
                    <td style="width:30px" class="text-center"><a class="btn-sm btn-warning" href="{% url 'plataform:item_view' item.id %}">
                        <i class="fa fa-edit"></i></a>
                    </td>
                    <td style="width:30px" class="text-center"><a class="btn-sm btn-danger" href="{% url 'plataform:item_delete' item.id %}"
                        onclick="return confirm('Você tem certeza que deseja excluir este item ?')">
                        <i class="fa fa-trash"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>

        {% include 'pagination.html' %}
        
    </section>

</main>

{% endblock %}

plataform/templates/items/item_update.html
{% extends 'company/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block container %}

<main class="container-fluid py-3">

    {% include 'breadcrumb.html' %}
        
    <section class="row my-2">

        <div class="col-md-10">
            <h3 class="text-success">Alterar Item</h3>
        </div>

        <div class="col-md-2">
            <a href="{% url 'plataform:items' %}">
                <button type="button" class="btn btn-success btn-sm px-5">
                    <span class="fa fa-arrow-left"></span> Voltar
                </button>
            </a>
        </div>

    </section>
    
    <section class="container-fluid mb-3">

        {% include 'messages.html' %}

        <section class="row">

            <div class="col-md-12 border border-success py-2">

                <form action="{% url 'plataform:item_update' item.id %}" method="POST">
                    {% csrf_token %}

                    <input type="hidden" class="form-control" name="company" value="{{ company_id }}">

                    <div class="row">
                        <div class="col-sm-1">
                            <span>ID</span>
                            <input type="text" value="{{ item.id }}" class="form-control" disabled name="id">
                        </div>
                        <div class="col-sm-5">
                            <span>Nome *</span>
                            <input type="text" value="{{ item.title }}" class="form-control" name="title">
                        </div>
                        <div class="col-sm-2">
                            <span>Referencia</span>
                            <input type="text" value="{{ item.reference }}" class="form-control" name="reference">
                        </div>
                        <div class="col-sm-2">
                            <span>Local</span>
                            <input type="text" value="{{ item.location }}" class="form-control" name="location">
                        </div>
                        <div class="col-sm-2">
                            <span>Un Med</span>
                            <select name="un_med" class="form-control">      
                                {% if item.un_med_id == None %}
                                    <option value="">Sem UnMed</option>
                                {% else %}
                                    <option value="{{ item.un_med_id }}">
                                        {{ item.un_med }}
                                    </option>
                                {% endif %}                        
                                <option disabled value=""> . Escolha uma UnMed</option>
                                {% for un_med in un_meds %}
                                    <option value="{{ un_med.id }}">{{ un_med }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-3">
                            <span>Tipo Item</span>
                            <select name="type_item" class="form-control">
                                <option value="{{ item.type_item }}">{{ item.get_type_item_display }}</option>
                                <option disabled value=""> > Escolha uma Opção</option>
                                <option value="1">Produto para Revenda</option>
                                <option value="2">Produção Própria</option>
                                <option value="3">Serviço Prestado</option>
                                <option value="4">Matéria-Prima</option>
                                <option value="5">Consumo e Utilização</option>
                                <option value="6">Ativo Patrimonial</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Controla Estoque</span>
                            <select name="stock_control" class="form-control">
                                {% if item.stock_control == False %}
                                    <option value="0">Não</option>
                                {% else %}
                                    <option value="1">Sim</option>
                                {% endif %}
                                <option disabled value=""> > Escolha uma Opção</option>
                                <option value="0">Não</option>
                                <option value="1">Sim</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Saldo Inicial</span>
                            <input type="text" value="{{ item.stock_qtd|floatformat:3 }}" class="form-control" name="stock_qtd">
                        </div>
                        <div class="col-sm-2">
                            <span>Custo</span>
                            <input type="text" value="{{ item.price_custom|floatformat:2 }}" class="form-control" name="price_custom">
                        </div>
                        <div class="col-sm-3">
                            <span>Marca</span>
                            <select name="brand" class="form-control">
                                {% if item.brand_id == None %}
                                    <option value="">Sem Marca</option>
                                {% else %}
                                    <option value="{{ item.brand_id }}">
                                        {{ item.brand }}
                                    </option>
                                {% endif %}
                                <option disabled value=""> >>> Escolha uma Marca</option>
                                {% for brand in brands %}
                                    <option value="{{ brand.id }}">{{ brand }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-2">
                            <span>Status</span>
                            <select class="form-control" name="status">
                                <option value="{{ item.status }}">{{ item.get_status_display }}</option>
                                <option disabled value=""> . Escolha uma Opção</option>                     
                                <option value="A">Ativo</option>
                                <option value="I">Inativo</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <span>Preço A Vista</span>
                            <input type="text" value="{{ item.price_in_cash|floatformat:2 }}" class="form-control" name="price_in_cash">
                        </div>
                        <div class="col-sm-2">
                            <span>Preço A Prazo</span>
                            <input type="text" value="{{ item.price_term|floatformat:2 }}" class="form-control" name="price_term">
                        </div>
                        <div class="col-sm-2">
                            <span>Preço Promoção</span>
                            <input type="text" value="{{ item.price_promotion|floatformat:2 }}" class="form-control" name="price_promotion">
                        </div>
                        <div class="col-sm-4">
                            <span>Categoria</span>
                            <select name="category" class="form-control">
                                {% if item.category_id == None %}
                                    <option value="">Sem Categoria</option>
                                {% else %}
                                    <option value="{{ item.category_id }}">
                                        {{ item.category }}
                                    </option>
                                {% endif %}
                                <option disabled value=""> >>> Escolha uma Categoria</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="row mt-2">
                        <div class="col-sm-12">
                            <span>Descrição</span>
                            <input type="text" value="{{ item.description }}" class="form-control" name="description">
                        </div>
                    </div>
                
                    <div class="row my-3">
                        <div class="col-sm-10">
                            <h6>* Nome não pode fica vazio.</h6>
                        </div>
                        <div class="col-sm-2">
                            <input type="submit" class="btn btn-success btn-sm px-5" value="Alterar">
                        </div>
                    </div>
                    
                </form>
            
            </div>

        </section>
        
    </section>
    
</main>

{% endblock %}

plataform/templates/items/modal_un_med.html
<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalUnMed">
  <i class="fa fa-plus"></i>
</button>           

<div class="modal fade" id="modalUnMed" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
                <h4 class="modal-title titulo" id="exampleModalLabel">Cadastrar Unidade Medida</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
          </div>
          
          <div class="modal-body">
              <form action="{% url 'un_med_create' %}" method="POST">
                {% csrf_token %}

                <span>Nome:</span>
                <input type="text" class="form-control mb-2" name="un_med">

                <span>Descrição:</span>
                <input type="text" class="form-control" name="description">

                <div class="text-right">
                    <input type="submit" class="btn btn-success btn-sm mt-3 px-5" value="Salvar">
                </div>
              </form>
          </div>
      </div>
  </div>
</div>